export const userList = [
  {
    id: "8f1c8d9748a93cc2f1ff2d781c27172c",
    firstName: "Alexandr",
    lastName: "Hambardzumyan",
    phone: "+37493114415",
    email: "alexanhambarcumyan@gmail.com",
    education: "Shushi Technology university",
    workExperience: "AIPC",
    trainings: "---",
    imagePath: "./CVBRIEF/imgsAlexandrHambardzumyan.jpg.jpg",
  },
  {
    id: "ab345bab810ba509e0c8ee0a2f7bc167",
    firstName: "Anahit",
    lastName: "Khechumyan",
    phone: "+37444148000",
    email: "Khechumyan63@gmail.com",
    education: "Yerevan State University",
    workExperience: "School Principal-School N67",
    trainings: "",
    imagePath: "./source/imagesForUsers/AnahitKhechumyan.jpg",
  },
  {
    id: "cb9cbee011abcdfc98b79a79d5f6bc59",
    firstName: "Ani",
    lastName: "Antonyan",
    phone: "notDefined",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "RELQ",
    imagePath: "./source/imagesForUsers/AniAntonyan.jpg",
  },
  {
    id: "c5bd75f1f50d741ab75f7e7120c0f3e7",
    firstName: "Anna",
    lastName: "Hayriyan",
    phone: "notDefined",
    email: "annhayriyan@gmail.com",
    education: "ASUE",
    workExperience: "Scott logistics",
    trainings: "RELQ",
    imagePath: "./source/imagesForUsers/AnnaHayriyan.jpg",
  },
  {
    id: "ccde2ac2c40ab9d48b140aeb1c4c5961",
    firstName: "Armenak",
    lastName: "Qocharyan",
    phone: "notDefined",
    email: "qocharyanarmenak@gmail.com",
    education: "Բարձրագույն զինվորական",
    workExperience: "ՀՀ ՊՆ",
    trainings: "Relq School",
    imagePath: "./source/imagesForUsers/ArmenakQocharyan.jpg",
  },
  {
    id: "d341660829b1f0f1d1a916b1bf508187",
    firstName: "Arusyak",
    lastName: "Aghajanyan",
    phone: "notDefined",
    email: "aghajanyanarusyak@gmail.com",
    education: "YSUGU",
    workExperience: "InecoBank CJSC, Risk meneger",
    trainings:
      "BasicItCenter,UNDP Armenia Accelerator5,HTI Armenia C++ basic, SmartCode,Relq Technology",
    imagePath: "./source/imagesForUsers/ArusyakAghajanyan.jpg",
  },
  {
    id: "950aef0eb630accad3eccef0eb751ad1",
    firstName: "Afina",
    lastName: "Panyan",
    phone: "notDefined",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq",
    imagePath: "./source/imagesForUsers/AfinaPanyan.jpg",
  },
  {
    id: "da0baac444f220e8a73693f00041aca5",
    firstName: "Babken",
    lastName: "Tadevosyan",
    phone: "notDefined",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq",
    imagePath: "./source/imagesForUsers/BabkenTadevosyan.jpg",
  },
  {
    id: "ca6e0da8d5981937aeac7df07d92db4a",
    firstName: "Hasmik",
    lastName: "Gevorgyan",
    phone: "notDefined",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq",
    imagePath: "./source/imagesForUsers/HasmikGevorgyan.jpg",
  },
  {
    id: "a1fbe88bdffefb5b963bf64a03909070",
    firstName: "Hermine",
    lastName: "Melkumyan",
    phone: "notDefined",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq",
    imagePath: "./source/imagesForUsers/HermineMelkumyan.jpg",
  },
  {
    id: "d83ddc7c27749495b4e049c460dcea10",
    firstName: "Hermine",
    lastName: "Sahakyan",
    phone: "notDefined",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq",
    imagePath: "./source/imagesForUsers/HermineSahakyan.jpg",
  },
  {
    id: "d9c9145f556b01aba58c836473c1089e",
    firstName: "Larine",
    lastName: "Danielyan",
    phone: "notDefined",
    email: "danielyanlari@gmail.com",
    education: "Economics and Menegment",
    workExperience: "Martuninsky district Medical Association",
    trainings: "Relq",
    imagePath: "./source/imagesForUsers/LarineDanielyan.jpg",
  },
  {
    id: "ba2e7839740f7118d87ccdde1aaaef94",
    firstName: "Liana",
    lastName: "Dashyan",
    phone: "notDefined",
    email: "dashyanlian@gmail.com",
    education: "YSU",
    workExperience: "GYU NGO",
    trainings: "Relq",
    imagePath: "./source/imagesForUsers/LianaDashyan.jpg",
  },
  {
    id: "8477bd0f0f7df27cfc29863664982ac7",
    firstName: "Lusine",
    lastName: "Yeremyan",
    phone: "notDefined",
    email: "lusineer@gmail.com",
    education: "Economist",
    workExperience: "Municipality",
    trainings: "Relq, MIC",
    imagePath: "./source/imagesForUsers/LusineYeremyan.jpg",
  },
  {
    id: "c8e7cbf708a2f3dfcf9765ef29f186ca",
    firstName: "Lusine",
    lastName: "Petrosyan",
    phone: "notDefined",
    email: "plusine99@gmail.com",
    education: "Armenian State University faculty of Radiophysics",
    workExperience: "-----",
    trainings: "Relq",
    imagePath: "./source/imagesForUsers/LusinePetrosyan.jpg",
  },
  {
    id: "dcf924cc259f9911d6e125e687b96588",
    firstName: "Karen",
    lastName: "Darbinyan",
    phone: "notDefined",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "./source/imagesForUsers/KarenDarbinyan.jpg",
  },
  {
    id: "9ffcb20b85668089e81f9b00a07bf79d",
    firstName: "Marat",
    lastName: "Harutyunyan",
    phone: "notDefined",
    email: "maratharutyunyan.mh.mh@gmail.com",
    education: "ASIPCS",
    workExperience: "EL Market",
    trainings: "Relq School",
    imagePath: "./source/imagesForUsers/MaratHarutyunyan.jpg",
  },
  {
    id: "8bbf94836b41d616ae64a17cf84457b0",
    firstName: "Narek",
    lastName: "Tovmasyan",
    phone: "notDefined",
    email: "Narektom333@gmail.com",
    education: "ASUE",
    workExperience: "Ameria Bank",
    trainings: "Relq School",
    imagePath: "./source/imagesForUsers/NarekTovmasyan.jpg",
  },
  {
    id: "9701237b19a3d0b1fb9d2236064a7712",
    firstName: "Seda",
    lastName: "Shahnazaryan",
    phone: "+37498313871",
    email: "shahnazaryan.seda@mail.ru",
    education: "Higher Education:Historian",
    workExperience: "15 years",
    trainings: "TechBoost4Women,RELQ technology school",
    imagePath: "./CVBRIEF/imgs/seda.jpg",
  },
  {
    id: "8b81628c0afe93e491874d82b0af8cfc",
    firstName: "Seryozha",
    lastName: "Asatryan",
    phone: "notDefined",
    email: "seryozha.asatryan02@gmail.com",
    education: "Economics",
    workExperience: "-----",
    trainings: "Relq School",
    imagePath: "./source/imagesForUsers/SeryozhaAsatryan.jpg",
  },
  {
    id: "93ef620cadf6371ad5c3c28203ceec58",
    firstName: "Sevak",
    lastName: "Stepanyan",
    phone: "notDefined",
    email: "stepanyansevak9@gamil.com",
    education: "Economics and Menegment",
    workExperience: "-----",
    trainings: "Relq School",
    imagePath: "./source/imagesForUsers/SevakStepanyan.jpg",
  },
  {
    id: "9022ea060d7df404b1f33e1ea77c3bc3",
    firstName: "Silva",
    lastName: "Ohanyan",
    phone: "notDefined",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq School",
    imagePath: "./source/imagesForUsers/SilvaOhanyan.jpg",
  },
  {
    id: "d3108be2c53f6711cfc18335ed2c0f66",
    firstName: "Suren",
    lastName: "Galstyan",
    phone: "notDefined",
    email: "notDefined",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq School",
    imagePath: "./source/imagesForUsers/SurenGalstyan.jpg",
  },
  {
    id: "c730005faec9eb73f2924b8fc443fc58",
    firstName: "Tigran",
    lastName: "Martirosyan",
    phone: "notDefined",
    email: "martirosyant01@mail.ru",
    education: "-----",
    workExperience: "-----",
    trainings: "Relq School",
    imagePath: "./source/imagesForUsers/TigranMartirosyan.jpg",
  },
];
